name: Build and Release
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bundle:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Run setup
        run: ./.vscode/setup.sh
      - name: Run build
        run: ./.vscode/build.sh
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $DATE
      - name: Create release
        if: steps.check.outputs.triggered == 'true'
        env:
          TAG_NAME: nightly-tag-${$DATE}
          RELEASE_NAME: nightly-release-${$DATE}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${TAG_NAME}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="{$RELEASE_NAME}" \
              --generate-notes
