name: Build and Release
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bundle:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Run setup
        run: ./.vscode/setup.sh
      - name: Run build
        id: build
        run: ./.vscode/build.sh
      - name: Get current date
        id: date
        run: echo "NOW=$(date + '%Y%m%d-T%H%M%S')" >> $GITHUB_ENV
      - name: Generate Tag
        env:
            NAME: "nightly-${{ env.NOW }}"
        run: echo "$NAME"
      - name: Nightly Release
        if: steps.build.outcome == 'success'
        env:
          NAME: "nightly-${{ env.NOW }}"
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          name: ${ NAME }
          tag_name: ${ NAME }
          files: "./out/Decky\ Sunshine.zip"
