name: Build and Release
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bundle:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4  
      - name: Run setup
        run: ./.vscode/setup.sh
      - name: Run build
        run: ./.vscode/build.sh
      - name: Get current date
        id: date
        run: echo "NOW=$(date + '%Y%m%d-T%H%M%S')" >> $GITHUB_ENV
      - name: Create release
        if: steps.check.outputs.triggered == 'true'
        env:
          TAG_NAME: nightly-tag-${{ env.NOW }}
          RELEASE_NAME: nightly-release-${{ env.NOW }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${TAG_NAME}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="{$RELEASE_NAME}" \
              --generate-notes
